name: Autocheck PR - based on rules of CONTRIBUTING.MD

on:
  pull_request:
    branches:
      - dev
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install pipenv
      run: pip install pipenv
    - name: Check pipenv path
      id: pipenv_path
      run: which pipenv
    - name: Install dependencies
      run: ${{ steps.pipenv_path.outputs.stdout }} install --dev
    - name: Build vlinder package
      run: ${{ steps.pipenv_path.outputs.stdout }} run pip install .
    - name: Run unit tests
      run: ${{ steps.pipenv_path.outputs.stdout }} run python -m pytest

  pep8:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install pre-commit
      run: pip install pre-commit
    - name: Run pre-commit
      run: pre-commit run --all-files
